## Training nueron

In [1]:
import torch
from torch import nn

In [28]:
print(torch.cuda.is_available())

True


In [2]:

# Input: Temperature in °C
X1 = torch.tensor([[10]], dtype=torch.float32) 
# Actual value: Temperature °F
y1 = torch.tensor([[50]], dtype=torch.float32) 

In [3]:

# Input: Temperature in °C
X2 = torch.tensor([[37.78]], dtype=torch.float32) 
# Actual value: Temperature °F
y2 = torch.tensor([[100.0]], dtype=torch.float32) 


In [16]:

model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001) # this use Stochastic Gradient Descent algorithm

In [17]:

print(model.bias)


Parameter containing:
tensor([-0.5720], requires_grad=True)


In [6]:

# Training pass
# Clear old gradients → predict → calculate error → compute gradients → update weights → check the result.
optimizer.zero_grad() # clear old gradient
outputs = model(X1) # predict
loss = loss_fn(outputs, y1) # calculate loss
loss.backward() # calculate gradient
optimizer.step() # update weights

print(model.bias)


y1_pred = model(X1)
print("y1_pred =", y1_pred)

Parameter containing:
tensor([0.4372], requires_grad=True)
y1_pred = tensor([[5.9641]], grad_fn=<AddmmBackward0>)


## training neuron2

In [7]:
for i in range(0, 10000):
    # Training pass
    optimizer.zero_grad()
    outputs = model(X1)
    loss = loss_fn(outputs, y1)
    loss.backward()
    optimizer.step()

    optimizer.zero_grad()
    outputs = model(X2)
    loss = loss_fn(outputs, y2)
    loss.backward()
    optimizer.step()

    if i % 1000 == 0: 
        print(model.bias)
        print(model.weight)

y1_pred = model(X1)
print("y1_pred =", y1_pred)

Parameter containing:
tensor([0.6160], requires_grad=True)
Parameter containing:
tensor([[4.8578]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
Parameter containing:
tens

## batch learning

In [22]:
X = torch.tensor([
    [10],
    [37.78]
] , dtype=torch.float32)

In [23]:
Y = torch.tensor([
    [50],
    [100]
] , dtype=torch.float32)

In [24]:

model = nn.Linear(1, 1)
loss_fn = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.0001)


In [26]:
for i in range(0, 100000):
    # Training pass
    optimizer.zero_grad()
    outputs = model(X)
    loss = loss_fn(outputs, Y)
    loss.backward()
    optimizer.step()


    if i % 1000 == 0: 
        print(model.bias)
        print(model.weight)

y_pred = model(X)
print("y_pred =", y_pred)

Parameter containing:
tensor([12.4743], requires_grad=True)
Parameter containing:
tensor([[2.4109]], requires_grad=True)
Parameter containing:
tensor([13.4355], requires_grad=True)
Parameter containing:
tensor([[2.3809]], requires_grad=True)
Parameter containing:
tensor([14.3495], requires_grad=True)
Parameter containing:
tensor([[2.3523]], requires_grad=True)
Parameter containing:
tensor([15.2184], requires_grad=True)
Parameter containing:
tensor([[2.3251]], requires_grad=True)
Parameter containing:
tensor([16.0446], requires_grad=True)
Parameter containing:
tensor([[2.2992]], requires_grad=True)
Parameter containing:
tensor([16.8301], requires_grad=True)
Parameter containing:
tensor([[2.2746]], requires_grad=True)
Parameter containing:
tensor([17.5769], requires_grad=True)
Parameter containing:
tensor([[2.2513]], requires_grad=True)
Parameter containing:
tensor([18.2870], requires_grad=True)
Parameter containing:
tensor([[2.2290]], requires_grad=True)
Parameter containing:
tensor([18

KeyboardInterrupt: 

In [29]:

measurements = torch.tensor([
    [37.5]
], dtype=torch.float32)

model.eval()
with torch.no_grad():
    prediction = model(measurements)
    print(prediction)


tensor([[99.7283]])
